### ISSUE TITLE
Update OpenBioLink Link

### ISSUE THREAD

**Issue by ddomingof** [pybel/openbiolink-bel#1]
https://stackoverflow.com/questions/58219778/how-to-get-a-direct-link-to-a-file-in-github-lfs-large-file-storage

**Comment by cthoyt** [comment]
Closed with d13a484f49f5bc6d5cde9e0c758c3eb2139ba711. Now, the vienna group is redistributing the BEL export themselves via zenodo. The readme has been updated accordingly
